apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-7
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app-7
          image: odilontalk/sample-app:latest
          env:
          - name: ENV
            value: "lab-us-2"
          - name: IDP_ENDPOINT
            value: "idp-lab-us-2"