apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app-1
          image: odilontalk/sample-app:latest
          env:
          - name: ENV
            value: "ti-us-2"
          - name: IDP_ENDPOINT
            value: "idp-ti-us-2"