apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: app-1
          imagePullPolicy: Always
          image: odilontalk/sample-app:latest
          ports:
            - containerPort: 5000